# Generated by Django 6.0.4 on 2026-04-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact_experience_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
